feat:add filters, searching, sorting
jerubrin/online-store pull request #16
Opened 2022-12-20 21:40 UTC by LoginovskyMax

фильтры вроде работают так как нужно, потестил немного, осталось только фильтры на цену и сток добавить

2022-12-21 16:39 UTC, jerubrin requested changes
В классе CardList - линтер выдает ошибки, проверь через `npm run lint`
Поправил все, на что ругался es-lint

2022-12-21 16:51 UTC, jerubrin commented
1. Там есть функция `getProducts` - она выдает все объекты сразу отфильтрованные по query запросу
2. И есть функция `setParams` - в которую передаются `QueryParams` и из них формируется query строка, там все само должно переирсовываться.

2022-12-22 10:13 UTC, LoginovskyMax commented
Згачит мои функции не нужны тогда,  но как твоими пользоваться не знаю)))

2022-12-22 10:21 UTC, jerubrin commented
> Згачит мои функции не нужны тогда, но как твоими пользоваться не знаю)))

На самом деле все просто - передаешь туда нужные параметры и все

`setParams({ brand: 'Apple' } as Partial<QueryParams>);`

А забираешь не из самого JSON файла, а из функции

`getProducts()` которые изначально складываются в `loadedData` - там уже ничего по идее не нужно фильтровать

Вроде такого и все самом перерендериваеться должно.

2022-12-22 11:53 UTC, LoginovskyMax commented
Сейчас попробую,  мультирейндж сделал,  добавил тоже

2022-12-23 17:08 UTC, LoginovskyMax commented
Если норм конфликт решил, то все должно работать))
Линтером прошелся в конце по коду

2022-12-24 03:28 UTC, jerubrin approved these changes

2022-12-24 03:28 UTC, merged